#
# Variables
#

$browser = zen-browser
$terminal = kitty
$mainMod = SUPER

source = ./colors.conf
source = ./monitors.conf

#
# Environment variables
#

env = HYPRSHOT_DIR,$HOME/Pictures/screenshots

#
# Autostart
#

exec-once = quickshell
exec-once = swayosd-server
exec-once = swww-daemon # wallpaper daemon
exec-once = $wallpaper-script

#
# Windows and workspaces
#

# Ignore maximize requests from apps
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

source = ./bindings.conf
source = ./looks.conf
source = ./input.conf
