foreground         #c1c0c0
background         #090404
background_opacity 1.0
cursor             #c1c0c0

active_tab_foreground     #090404
active_tab_background     #c1c0c0
inactive_tab_foreground   #c1c0c0
inactive_tab_background   #090404

active_border_color   #c1c0c0
inactive_border_color #090404
bell_border_color     #7c5470

color0       #090404
color8       #665353
color1       #7c5470
color9       #7c5470
color2       #7d6f69
color10      #7d6f69
color3       #926f84
color11      #926f84
color4       #ac9a92
color12      #ac9a92
color5       #b4b4b4
color13      #b4b4b4
color6       #fbb3eb
color14      #fbb3eb
color7       #c1c0c0
color15      #c1c0c0
